using Microsoft.AspNetCore.DataProtection;
using Microsoft.IdentityModel.Tokens;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Org.BouncyCastle.Crypto.Parameters;// Provides classes for BouncyCastle cryptographic parameters.
using Org.BouncyCastle.Security;// Provides classes for security operations in BouncyCastle.
using Org.BouncyCastle.OpenSsl;// Provides classes for handling OpenSSL's PEM format in BouncyCastle.


namespace MVC6Crud.Models
{
    class AES_ENCRYPTION
    {
        // Initialization Vector length for the AES encryption.
        private int ivLength;
        // The cipher algorithm used for encryption.
        private string cipherAlgo;
        // The secret key used for AES encryption.
        private byte[] secretKey;


        // Constructor for AES_ENCRYPTION class that takes the base64 encoded secret key.
        public AES_ENCRYPTION(string base64SecretKey)
        {
            // 128 bits or 16 bytes is the initialization vector length.
            ivLength = 16;
            // 256 bits is key size.
            cipherAlgo = "AES";
            // 256 bits secret_key encoded in base64_decode expected
            secretKey = Convert.FromBase64String(base64SecretKey);
        }

        // Method to encrypt the given string data using AES encryption.
        public string Encrypt(string data)
        {
            // initialization vector
            byte[] iv = new byte[ivLength];
            Random random = new Random();
            random.NextBytes(iv);
            using (Aes aes = Aes.Create())
            {
                aes.Key = secretKey;
                aes.IV = iv;
                aes.Mode = CipherMode.CBC;
                aes.Padding = PaddingMode.PKCS7;

                ICryptoTransform encryptor = aes.CreateEncryptor(aes.Key, aes.IV);

                byte[] rawData = Encoding.UTF8.GetBytes(data);
                byte[] encryptedData = encryptor.TransformFinalBlock(rawData, 0, rawData.Length);

                string encryptedBase64 = Convert.ToBase64String(iv.Concat(encryptedData).ToArray());

                return encryptedBase64;
            }
        }
    }

    // JWT_Generator class responsible for generating JWT tokens.
    class JWT_Generator
    {

        private string user_ref_id;
        //Plural Merchant ID
        private string mid;
        //Merchant name in PLural
        private string iss;
        //Merchant source system name used during on-boarding to Subscription.
        private string aggr;
        //Get this value from subscription onboarding team
        private string secret;
        //lifetime of jwt
        private int lifetime;
        //private key generated by merchant
        private string privateKey;

        public JWT_Generator()
        {
            user_ref_id = "usr-3c05374d1f594037b5c175a76a16dfbe"; // User Reference ID - get from Onboarding team
            mid = "648"; // Merchant-Id - get from Onboarding Team
            iss = "Payman"; // Merchant-name used during onboarding
            aggr = "PLURAL"; // Merchant-source-system-name used during onboarding
            secret = "e6EzFvCWeoggrc7pAmb2aqn3cSSIbuR25NX/Jt6fTPQ=";
            lifetime = 30 * 60;
            privateKey = @"-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDLgwnJcgr/axyAoPxzRq3lZ+b8gcU52eze1E39b5r6IivkGt8go3s0hvEGHMTjqXUdBfpE2m9Gfgs1+GqM3anUr9R1Aos2v4Gj+8d9FILr7XoeM+F+sSizsKIRqXbv0L10m0vpz/t9SvBgPjme16eTIW+24Pwpz4ySyH3PvLzMIDBxBWgJUaWgLxXbjaWdHPpxvRDoOBqbiovOsxpuKuWmkWDwnsdoqngbx83fr3wwOJ8NmTPwUIlWF9hYChNh1sTyaHl4NPpzd6C4neAqB2LgRWex/fo7B2N6PdCxDD9bH7UqctvlxdjljxYMmIvW/MFzHDpF2732SpVFhPbWexrZAgMBAAECggEABi32cB18ZAEWnnlE8SMmSJ79DpHKMVWCscl0jMuEwy+icYy3VcBhD1lBnFPnTppoqfbygIC5fER7hqoCYkCg1Yp5QwxOudzazOXqSswCpbNST/R3Vmd+uuYUJcElkWafOhk1FuZv1oAeCG4bRc16kyciw0TVo1dgB1z7JQGwIeqSbrMuH0jYS0IqAvim13o04DtZUitFTo7qpvEe0DuXSfqmVtkYPuRCsvkRlsnIoo+1HoaexxPWuPDEL/Ps9kxlRBiFkVmPMNgc21XBQjzoMDR2K3ZmNHYoQm6LT1399vF7Q6TH24wr1ahxQsyD/v1OF7vDBohrS5UcyMETSGs2OQKBgQDtSvabxuYLF3x86aO33hTqRN7LRDFYo90JgnuycxpWg/OJky8kfRni4+e3jxA7f+refjU+DpCasMP2Im6kSSvifxo2RRhGiqvmo3d9obn+j4E99w6m/o2mdjAc7muYzm0EKvP45r0tfIenSuYGMuRYXlZojrXjEQfMFs81rUz49wKBgQDbjk8DhClHKO2cJMVrBzGyuVFWK0hu4s8Oy1hezTc2rxpTsu2Q6XD9QrYTwq4/31fT05raIj/UTWbHGhAf0sSrU/GuwwwquUmUE0Uu0ZuNVpmpnIB6O6g25NGHxpOdbJvEJlcSS3G4z6aTIbGl3Y9lFpeq08cyHY3dyFP7HYnmrwKBgQDmV0tV4dgy0iScmKu88w44bowaomKIWeBZt9jdW5AohUPluwMbF3kGXxbyfyRRrZVPTxHd4IOMNaSzi679OK4p2hmWrrGm4DuH0gxO3qvOqHzbqrQFdLoJ6VZA70tw9IiscAmOBmWC/wwrX7A0Ojigc0rLiiSTe1enTEjuIQDD9wKBgQCKXpKvfaBiJ4owaQA+ZqdMovx+2QJqV+j0wvTrslvEy/BEpbSRKn46Lsv/gic9O+3nIyoppYIis7E9c9CLrdKiw2HCqUxGtMWJW+ezDQkCt3xaZ7aU0no+NlFTR7QKd8NniF5Bumhud/fcLFUAWrUfmXB2ice1bujUyIcc8M3TIwKBgAtX1kiBSkPPISLbG3240t87EyXd5AcOtWQYwMaiYWWM1tuLa59Mw5LHbFMdbLu1QsZtX0Lav2OTx12lhF/qpzqRsYVPLGApQcoqp93w7X4qtC4mMfGFg1hvP271pXaDU28VhUalG5Z2cHZ6HZAM61A6sUBV4cl+ovWOCQ7e4T3M
-----END PRIVATE KEY-----";
            //In a alternate approach you can placed this key in a pem file and get the same when required.

        }

        // Method to construct the payload for the JWT token.
        public Dictionary<string, object> GetPayload()
        {
            AES_ENCRYPTION encryptor = new AES_ENCRYPTION(secret);
            string data = JsonSerializer.Serialize(new { mid = mid, iss = iss, agr = aggr });
            string encryptedData = encryptor.Encrypt(data);

            Dictionary<string, object> claims = new Dictionary<string, object>
        {
            { "data", encryptedData },
            { "srv", "Payout" },
            { "sub", Convert.ToBase64String(Encoding.UTF8.GetBytes(user_ref_id)) }
        };
            return claims;
        }

        // Method to generate the JWT token with the given payload and sign it with RSA private key.
        public string GenerateToken()
        {
            var claims = GetPayload();

            RsaSecurityKey rsaKey = CreateRsaSecurityKeyFromPem(privateKey);

            var tokenHandler = new JwtSecurityTokenHandler();
            var tokenDescriptor = new SecurityTokenDescriptor
            {
                Audience = "Plural",
                Claims = claims,
                IssuedAt = DateTime.UtcNow,
                Expires = DateTime.UtcNow.AddMinutes(30), // Token expiry set to 30 minutes
                SigningCredentials = new SigningCredentials(rsaKey, SecurityAlgorithms.RsaSha256)
            };

            var token = tokenHandler.CreateToken(tokenDescriptor);
            return tokenHandler.WriteToken(token);

        }

        public static RsaSecurityKey CreateRsaSecurityKeyFromPem(string pemString)
        {
            RSA rsa = CreateRsaProviderFromPem(pemString);
            return new RsaSecurityKey(rsa);
        }

        private static RSA CreateRsaProviderFromPem(string pemString)
        {
            using (StringReader stringReader = new StringReader(pemString))
            {
                PemReader pemReader = new PemReader(stringReader);
                object pemObject = pemReader.ReadObject();
                if (pemObject is RsaPrivateCrtKeyParameters parameters)
                {
                    RSAParameters rsaParameters = DotNetUtilities.ToRSAParameters(parameters);
                    RSA rsa = RSA.Create();
                    rsa.ImportParameters(rsaParameters);
                    return rsa;
                }
                else
                {
                    throw new Exception("Unsupported PEM object was found.");
                }
            }
        }
    }


    // JwtToken is the entry point class for the application that generates JWT tokens.
    // how to generate the token
    //class JwtToken
    //{
    //    static void Main(string[] args)
    //    {
    //        // Create an instance of JWT_Generator and output the generated token.
    //        JWT_Generator generator = new JWT_Generator();
    //        // Generate a JWT using the generator instance and output the result to the console.
    //        Console.WriteLine(generator.GenerateToken());
    //    }
    //}

}
