// Required NuGet Packages:
// System.IdentityModel.Tokens.Jwt - Provides classes for creating and validating JSON Web Tokens (JWT).
// Microsoft.IdentityModel.Tokens - Provides classes for various security token operations including signing credentials and security keys.
// BouncyCastle - A cryptography API that supplements the cryptographic functions provided by .NET.

using System;
using System.Collections.Generic;
using System.Security.Cryptography;// Provides cryptographic services, including secure encoding and decoding of data, as well as many other operations, such as hashing, random number generation, and message authentication.
using System.Text;//Contains classes representing ASCII and Unicode character encodings; abstract base classes for converting blocks of characters to and from blocks of bytes; and a helper class that manipulates and formats String objects without creating intermediate instances of String.
using System.Text.Json;// Provides high-performance, low-allocating, and standards-compliant tools to work with JSON.
using System.IdentityModel.Tokens.Jwt;// Provides classes for creating and validating JSON Web Tokens.
using System.Security.Claims;// Provides classes for implementing claims-based identity in your applications.
using Microsoft.IdentityModel.Tokens; // Provides classes for various security token operations.
using Org.BouncyCastle.Crypto.Parameters;// Provides classes for BouncyCastle cryptographic parameters.
using Org.BouncyCastle.Security;// Provides classes for security operations in BouncyCastle.
using Org.BouncyCastle.OpenSsl;// Provides classes for handling OpenSSL's PEM format in BouncyCastle.

//AES_ENCRYPTION class provides methods for AES encryption of data.
class AES_ENCRYPTION
{
    // Initialization Vector length for the AES encryption.
    private int ivLength;
    // The cipher algorithm used for encryption.
    private string cipherAlgo;
    // The secret key used for AES encryption.
    private byte[] secretKey;


    // Constructor for AES_ENCRYPTION class that takes the base64 encoded secret key.
    public AES_ENCRYPTION(string base64SecretKey)
    {
        // 128 bits or 16 bytes is the initialization vector length.
        ivLength = 16;
        // 256 bits is key size.
        cipherAlgo = "AES";
        // 256 bits secret_key encoded in base64_decode expected
        secretKey = Convert.FromBase64String(base64SecretKey);
    }

    // Method to encrypt the given string data using AES encryption.
    public string Encrypt(string data)
    {
        // initialization vector
        byte[] iv = new byte[ivLength];
        Random random = new Random();
        random.NextBytes(iv);
        using (Aes aes = Aes.Create())
        {
            aes.Key = secretKey;
            aes.IV = iv;
            aes.Mode = CipherMode.CBC;
            aes.Padding = PaddingMode.PKCS7;

            ICryptoTransform encryptor = aes.CreateEncryptor(aes.Key, aes.IV);

            byte[] rawData = Encoding.UTF8.GetBytes(data);
            byte[] encryptedData = encryptor.TransformFinalBlock(rawData, 0, rawData.Length);

            string encryptedBase64 = Convert.ToBase64String(iv.Concat(encryptedData).ToArray());

            return encryptedBase64;
        }
    }
}

// JWT_Generator class responsible for generating JWT tokens.
class JWT_Generator
{

    private string user_ref_id;
    //Plural Merchant ID
    private string mid;
    //Merchant name in PLural
    private string iss;
    //Merchant source system name used during on-boarding to Subscription.
    private string aggr;
    //Get this value from subscription onboarding team
    private string secret;
    //lifetime of jwt
    private int lifetime;
    //private key generated by merchant
    private string privateKey;

    public JWT_Generator()
    {
        user_ref_id = "usr-3c05374d1f594037b5c175a76a16dfbe"; // User Reference ID - get from Onboarding team
        mid = "648"; // Merchant-Id - get from Onboarding Team
        iss = "Payman"; // Merchant-name used during onboarding
        aggr = "PLURAL"; // Merchant-source-system-name used during onboarding
        secret = "0017B307F8D64D4D91F4312FFCE74548";
        lifetime = 30 * 60;
        privateKey = @"-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCnNf8cYOR95VqIcjhfAyjfmzIf8UXtDFidw7iNkVBRzHIqI9BAmjG7RF4P/fCWavO13mgI26rSMSv2rJKfHQ5aHbVTQ2g8pyKsXpklm+E3VrjxtsxxjyMwjS74NdrHqwkCBai81VahWXUM6WtMKWbsRMbY/5B539rOMwB3bm59sRapydUdIUiUFvuFmK2nn3f/UJ5/M7WrNv9reIBX1E45FTzrUJZSuoWU4CnkEb3LFmWPxjK5PneBqwdVlu1rMrrrLVOR2FpIly5G/IqRkhS85q1o2RAQEabfbqYkWXXFfiB/68Kh6PXxu7xCy35wqv1zSe5jPRgJBUR428FnBORXAgMBAAECggEAL3vrBXESkhn2urbNAVZRXiahdma699VAuRSirTkt+Py5EvR2qFHhe4+vspTnpJ+cs/ID0zgma2hhVrytKphCwh6bppiG2mqQMyjuDrsUmvV6sdG6fykp0hjV1NDeX0NX3IYk4/Mllc5kqhUDTm6XdtMVMPxqV+HVLidXo5Ltt62D/AX+H7dwwyczui+FpO5KmgwjSiQyetSGOq93x6rTslkvu8dP3cJ745jP7rKI8DuU505p1xUjeZfzXvTS6p06wHaP7AKGZVQKQufMO2+OHbKBBQpL3UDFFn+5dFjLJ3LjHdBXgMjmExJGxOROFzkDO/nQSJIqzo978tVAUoELwQKBgQDTTlbYkvrXDy1mVhfQuuEM3rAhjt8WNSbMouKtSjhVb/dsYRzcS5auE3eEJI2HKpKPoNe3uEwDEfWeTd2e17UKz0iWDQymmX0nmc8c1KiFD/0QfYj7KudmNv+ESeIK/jf5OSYHSZAvHnQcji08umCOLkz4VzuKhiIb4hAtuMetNwKBgQDKlAZp8Ilykfd6LbY1WfY67JgbPqkLXwXomSk/VUQclphG550cZ6R1cVxGLthxL8FuGJePBkxWjL1/tsVtVzoaYv2JLANIEILAOPjJA9Lpk58sUxQYlnnZjugm7ZjAyXls6PDu0NLwgRnLGelHQw+m5Wbfl8uHznuE4f4jpaMR4QKBgFG7GmJYr4dhinjr0fhdYFD/DXddcLKBSomaczz92T5KuZQFGAmpfxXD19WX4donQFsnpmicc2I4nx1lFtSqsI8G0Beh4oPKGJuppW+MXcZiActQExy7YpeprDl57mG8JOBUF354GLnw+I5W++5iVJiKFiF0dEZHTYglb4aP00QPAoGANb2zPeOL8xL6HjWGQv0Mr3EYoRGsctHQlXYcVSrfmN3yo8zKB0EPhgB+xDelP9G1dOmdO1omYkeP9hOcqHcdeOaN8Bf2/uUyaqAyj9Et4L1C2tVnXWZ+CNM6jyk0/t/0EIpzcEeBzj/Rgenr0vXdbx8ofWSdn/eNGSGC9B369sECgYEAzQOEVvcHB/iPOGH6JyHJYfbB3U//YJKJAOXxsEh7kS8UOlcl0S3z0CCUzX7P2RHUcYCqcuZg9zo78ebauIqZyj4nRX++JSZPG1ZGlLRILs7DiPp8rRCZqry7oXM88Cv6EwKNyjw21ffCpmVYPZV9ahn16/1qmTyfDILJnVYOQtY=
-----END PRIVATE KEY-----";
        //In a alternate approach you can placed this key in a pem file and get the same when required.

    }

    // Method to construct the payload for the JWT token.
    public Dictionary<string, object> GetPayload()
    {
        AES_ENCRYPTION encryptor = new AES_ENCRYPTION(secret);
        string data = JsonSerializer.Serialize(new { mid = mid, iss = iss, agr = aggr });
        string encryptedData = encryptor.Encrypt(data);

        Dictionary<string, object> claims = new Dictionary<string, object>
        {
            { "data", encryptedData },
            { "srv", "Payout" },
            { "sub", Convert.ToBase64String(Encoding.UTF8.GetBytes(user_ref_id)) }
        };
        return claims;
    }

    // Method to generate the JWT token with the given payload and sign it with RSA private key.
    public string GenerateToken()
    {
        var claims = GetPayload();

        RsaSecurityKey rsaKey = CreateRsaSecurityKeyFromPem(privateKey);

        var tokenHandler = new JwtSecurityTokenHandler();
        var tokenDescriptor = new SecurityTokenDescriptor
        {
            Audience = "Plural",
            Claims = claims,
            IssuedAt = DateTime.UtcNow,
            Expires = DateTime.UtcNow.AddMinutes(30), // Token expiry set to 30 minutes
            SigningCredentials = new SigningCredentials(rsaKey, SecurityAlgorithms.RsaSha256)
        };

        var token = tokenHandler.CreateToken(tokenDescriptor);
        return tokenHandler.WriteToken(token);

    }

    public static RsaSecurityKey CreateRsaSecurityKeyFromPem(string pemString)
    {
        RSA rsa = CreateRsaProviderFromPem(pemString);
        return new RsaSecurityKey(rsa);
    }

    private static RSA CreateRsaProviderFromPem(string pemString)
    {
        using (StringReader stringReader = new StringReader(pemString))
        {
            PemReader pemReader = new PemReader(stringReader);
            object pemObject = pemReader.ReadObject();
            if (pemObject is RsaPrivateCrtKeyParameters parameters)
            {
                RSAParameters rsaParameters = DotNetUtilities.ToRSAParameters(parameters);
                RSA rsa = RSA.Create();
                rsa.ImportParameters(rsaParameters);
                return rsa;
            }
            else
            {
                throw new Exception("Unsupported PEM object was found.");
            }
        }
    }
}


// JwtToken is the entry point class for the application that generates JWT tokens.
// how to generate the token
class JwtToken
{
    static void Main(string[] args)
    {
        // Create an instance of JWT_Generator and output the generated token.
        JWT_Generator generator = new JWT_Generator();
        // Generate a JWT using the generator instance and output the result to the console.
        Console.WriteLine(generator.GenerateToken());
    }
}