// Required NuGet Packages:
// System.IdentityModel.Tokens.Jwt - Provides classes for creating and validating JSON Web Tokens (JWT).
// Microsoft.IdentityModel.Tokens - Provides classes for various security token operations including signing credentials and security keys.
// BouncyCastle - A cryptography API that supplements the cryptographic functions provided by .NET.

using System;
using System.Collections.Generic;
using System.Security.Cryptography;// Provides cryptographic services, including secure encoding and decoding of data, as well as many other operations, such as hashing, random number generation, and message authentication.
using System.Text;//Contains classes representing ASCII and Unicode character encodings; abstract base classes for converting blocks of characters to and from blocks of bytes; and a helper class that manipulates and formats String objects without creating intermediate instances of String.
using System.Text.Json;// Provides high-performance, low-allocating, and standards-compliant tools to work with JSON.
using System.IdentityModel.Tokens.Jwt;// Provides classes for creating and validating JSON Web Tokens.
using System.Security.Claims;// Provides classes for implementing claims-based identity in your applications.
using Microsoft.IdentityModel.Tokens; // Provides classes for various security token operations.
using Org.BouncyCastle.Crypto.Parameters;// Provides classes for BouncyCastle cryptographic parameters.
using Org.BouncyCastle.Security;// Provides classes for security operations in BouncyCastle.
using Org.BouncyCastle.OpenSsl;// Provides classes for handling OpenSSL's PEM format in BouncyCastle.

//AES_ENCRYPTION class provides methods for AES encryption of data.
class AES_ENCRYPTION
{
    // Initialization Vector length for the AES encryption.
    private int ivLength;
    // The cipher algorithm used for encryption.
    private string cipherAlgo;
    // The secret key used for AES encryption.
    private byte[] secretKey;


    // Constructor for AES_ENCRYPTION class that takes the base64 encoded secret key.
    public AES_ENCRYPTION(string base64SecretKey)
    {
        // 128 bits or 16 bytes is the initialization vector length.
        ivLength = 16;
        // 256 bits is key size.
        cipherAlgo = "AES";
        // 256 bits secret_key encoded in base64_decode expected
        secretKey = Convert.FromBase64String(base64SecretKey);
    }

    // Method to encrypt the given string data using AES encryption.
    public string Encrypt(string data)
    {
        // initialization vector
        byte[] iv = new byte[ivLength];
        Random random = new Random();
        random.NextBytes(iv);
        using (Aes aes = Aes.Create())
        {
            aes.Key = secretKey;
            aes.IV = iv;
            aes.Mode = CipherMode.CBC;
            aes.Padding = PaddingMode.PKCS7;

            ICryptoTransform encryptor = aes.CreateEncryptor(aes.Key, aes.IV);

            byte[] rawData = Encoding.UTF8.GetBytes(data);
            byte[] encryptedData = encryptor.TransformFinalBlock(rawData, 0, rawData.Length);

            string encryptedBase64 = Convert.ToBase64String(iv.Concat(encryptedData).ToArray());

            return encryptedBase64;
        }
    }
}

// JWT_Generator class responsible for generating JWT tokens.
class JWT_Generator
{

    private string user_ref_id;
    //Plural Merchant ID
    private string mid;
    //Merchant name in PLural
    private string iss;
    //Merchant source system name used during on-boarding to Subscription.
    private string aggr;
    //Get this value from subscription onboarding team
    private string secret;
    //lifetime of jwt
    private int lifetime;
    //private key generated by merchant
    private string privateKey;

    public JWT_Generator()
    {
        user_ref_id = "usr-a1e6864c1e61458087ae734f24b0524c"; // User Reference ID - get from Onboarding team
        mid = "19181"; // Merchant-Id - get from Onboarding Team
        iss = "Akshit"; // Merchant-name used during onboarding
        aggr = "Plural"; // Merchant-source-system-name used during onboarding
        secret = "8rNJVtbsSDjSFS1DK7bgGeTwEu9gRMPb6OyU5CpKDFQ=";
        lifetime = 30 * 60;
        privateKey = @"-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCurMdlSquva9EJ+fAfF3zASK4ghVBQ7bnoSnVP4ZF8J612WvV3iqsSGfMaAwhMPnnmalrFMmKtjwY9MmIdCvqM9jhqqBPg32oV/JJRUuhZbVN4TN8Ixj4qRJ163exH4bstQwXeTjF8b04YjNpEltr3M6lrsf1d+RpqnODeylVGgP8ikkP5stsa/svvFdHjD1fTLqJdpKJek6glMYOFi4jJRoL+xYdc5UO8KpCxjcJI1gzu1ujWnQzgMoQlsJhO7SM2ja1jz8+3hXM2OUJ+ePtYz1elHpk9uXzJAwedGhp3ZYimMFTUHHVRKyNiiUFwc8do0HfdQpLwdMyZkvP1BkwJAgMBAAECggEAB6tO7ePe1Urkj42SmIZNeMBcvfXuw/W5yUsnCtusziQesLtVEf23NIpA2MT0LAcX6nyDypixKZYzbez9zvE0LB3yPwf/TAGw4CNlU3529I9X+W0Ndde8HLZoO6kSLCSh7BVj0pIGCHvAS3jKj/WFXMksv2RQWPMMY0zK3QZu53ygahwqPhcXXqfr47XvhjiBensB8rWkfRR/CEXvAJIxOHcQA4xD9TORzRw+DdTxbJohNIntXD3SVhanhttHJen/PgOa9FyyxzDEyU6NP2qo4m3HfFJOaWXblhKsAq+wCPUMN6iXa1TlKSIDxL4LRpFDGF0yy7BxvZnuJO4uqGHJiQKBgQDcy8vOLDfamTGd+v/K8Z+3PFePz293fHnO8pkGnp9FjHHvBR9yX5LdgAKrU56mv6j5YuynCTM6z+yz3epto2/nUOncSQB50kxE3PjCRoFofoaHqtW8pRbPdNWkV8/T4PiIF1Z8w7B+kzQfqQoN/sWhCtn1MxjnYESaqaPwUnoIYwKBgQDKhnYnaVyFbDuHKGo72ka0Bg7hi+FNuEzHdm5BGImGvoVhB+9ikQai4FYu2SFGj4uT7pG0U+eSA62cPUFMZa/eU6gNTRHb0LmGucCkZLazn46fPU8ZuygXxDqfuXv1Iw1Le5ZV5cpnhqYtMVdXbz409zduLIFkj/0f3RgadlrHowKBgQChNUMm024scvGhMSQWHvjIJoyf+YqfKQkeqk5EYQhVFUgShiEBtvpaMx6/zJvnj8Rl4W58PuFirXFbmkmRp2UK9S7qoXpxd7QsC1KtNiFCFC9RWtAXnknbSqi6B0s8neOYKcIB8jcpE31ZKGio8z2EaZHdz2L9fHJaokWKMA3dlQKBgQCw5dn2etVRxUQJvodsWDBBtrjw0VmupTiLUSrkuSYHCAtAwcma8so1Inak3QtvsppcUJn8RP2UUJooSmjq7jc7nx6+336l3h7vSvi1nzLmmovdE5QwCYXvnHsIYN+hM0i9kemyhdDRtI8aEmsT+BsB8J3+IemziQGz/066bn7EuQKBgQCEhOqdQ0M3EOLsSWrMp2cRCf2Wfd21peZHHiVY2ehIA9JhEPrpWCFAXAbvYjH3r12/j0GmsVPnAdukgc9p/rZypJUnAUOFXfd7AqsNVZ07V1DLw49gbLKPIbhi7z5E8exhpUdKaH8y3oKsek7ibuBDe+JCDb5YyVyOyfha4T5fZQ==
-----END PRIVATE KEY-----";
        //In a alternate approach you can placed this key in a pem file and get the same when required.

    }

    // Method to construct the payload for the JWT token.
    public Dictionary<string, object> GetPayload()
    {
        AES_ENCRYPTION encryptor = new AES_ENCRYPTION(secret);
        string data = JsonSerializer.Serialize(new { mid = mid, iss = iss, agr = aggr });
        string encryptedData = encryptor.Encrypt(data);

        Dictionary<string, object> claims = new Dictionary<string, object>
        {
            { "data", encryptedData },
            { "srv", "Payout" },
            { "sub", Convert.ToBase64String(Encoding.UTF8.GetBytes(user_ref_id)) }
        };
        return claims;
    }

    // Method to generate the JWT token with the given payload and sign it with RSA private key.
    public string GenerateToken()
    {
        var claims = GetPayload();

        RsaSecurityKey rsaKey = CreateRsaSecurityKeyFromPem(privateKey);

        var tokenHandler = new JwtSecurityTokenHandler();
        var tokenDescriptor = new SecurityTokenDescriptor
        {
            Audience = "Plural",
            Claims = claims,
            IssuedAt = DateTime.UtcNow,
            Expires = DateTime.UtcNow.AddMinutes(30), // Token expiry set to 30 minutes
            SigningCredentials = new SigningCredentials(rsaKey, SecurityAlgorithms.RsaSha256)
        };

        var token = tokenHandler.CreateToken(tokenDescriptor);
        return tokenHandler.WriteToken(token);

    }

    public static RsaSecurityKey CreateRsaSecurityKeyFromPem(string pemString)
    {
        RSA rsa = CreateRsaProviderFromPem(pemString);
        return new RsaSecurityKey(rsa);
    }

    private static RSA CreateRsaProviderFromPem(string pemString)
    {
        using (StringReader stringReader = new StringReader(pemString))
        {
            PemReader pemReader = new PemReader(stringReader);
            object pemObject = pemReader.ReadObject();
            if (pemObject is RsaPrivateCrtKeyParameters parameters)
            {
                RSAParameters rsaParameters = DotNetUtilities.ToRSAParameters(parameters);
                RSA rsa = RSA.Create();
                rsa.ImportParameters(rsaParameters);
                return rsa;
            }
            else
            {
                throw new Exception("Unsupported PEM object was found.");
            }
        }
    }
}


// JwtToken is the entry point class for the application that generates JWT tokens.
// how to generate the token
class JwtToken
{
    static void Main(string[] args)
    {
        // Create an instance of JWT_Generator and output the generated token.
        JWT_Generator generator = new JWT_Generator();
        // Generate a JWT using the generator instance and output the result to the console.
        Console.WriteLine(generator.GenerateToken());
    }
}